//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankMVC.BankAccountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankAccountService.IBankAccountService")]
    public interface IBankAccountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAccountService/AddBankAccount", ReplyAction="http://tempuri.org/IBankAccountService/AddBankAccountResponse")]
        int AddBankAccount(Pocos.BankAccount bankAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAccountService/AddBankAccount", ReplyAction="http://tempuri.org/IBankAccountService/AddBankAccountResponse")]
        System.Threading.Tasks.Task<int> AddBankAccountAsync(Pocos.BankAccount bankAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAccountService/GetAllBankAccounts", ReplyAction="http://tempuri.org/IBankAccountService/GetAllBankAccountsResponse")]
        System.Collections.Generic.List<Pocos.BankAccount> GetAllBankAccounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAccountService/GetAllBankAccounts", ReplyAction="http://tempuri.org/IBankAccountService/GetAllBankAccountsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Pocos.BankAccount>> GetAllBankAccountsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAccountService/GetBankAccuntById", ReplyAction="http://tempuri.org/IBankAccountService/GetBankAccuntByIdResponse")]
        Pocos.BankAccount GetBankAccuntById(int bankAccountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAccountService/GetBankAccuntById", ReplyAction="http://tempuri.org/IBankAccountService/GetBankAccuntByIdResponse")]
        System.Threading.Tasks.Task<Pocos.BankAccount> GetBankAccuntByIdAsync(int bankAccountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAccountService/DeleteBankAccount", ReplyAction="http://tempuri.org/IBankAccountService/DeleteBankAccountResponse")]
        void DeleteBankAccount(Pocos.BankAccount bankAccountToDelete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankAccountService/DeleteBankAccount", ReplyAction="http://tempuri.org/IBankAccountService/DeleteBankAccountResponse")]
        System.Threading.Tasks.Task DeleteBankAccountAsync(Pocos.BankAccount bankAccountToDelete);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankAccountServiceChannel : BankMVC.BankAccountService.IBankAccountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankAccountServiceClient : System.ServiceModel.ClientBase<BankMVC.BankAccountService.IBankAccountService>, BankMVC.BankAccountService.IBankAccountService {
        
        public BankAccountServiceClient() {
        }
        
        public BankAccountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankAccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankAccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankAccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddBankAccount(Pocos.BankAccount bankAccount) {
            return base.Channel.AddBankAccount(bankAccount);
        }
        
        public System.Threading.Tasks.Task<int> AddBankAccountAsync(Pocos.BankAccount bankAccount) {
            return base.Channel.AddBankAccountAsync(bankAccount);
        }
        
        public System.Collections.Generic.List<Pocos.BankAccount> GetAllBankAccounts() {
            return base.Channel.GetAllBankAccounts();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Pocos.BankAccount>> GetAllBankAccountsAsync() {
            return base.Channel.GetAllBankAccountsAsync();
        }
        
        public Pocos.BankAccount GetBankAccuntById(int bankAccountId) {
            return base.Channel.GetBankAccuntById(bankAccountId);
        }
        
        public System.Threading.Tasks.Task<Pocos.BankAccount> GetBankAccuntByIdAsync(int bankAccountId) {
            return base.Channel.GetBankAccuntByIdAsync(bankAccountId);
        }
        
        public void DeleteBankAccount(Pocos.BankAccount bankAccountToDelete) {
            base.Channel.DeleteBankAccount(bankAccountToDelete);
        }
        
        public System.Threading.Tasks.Task DeleteBankAccountAsync(Pocos.BankAccount bankAccountToDelete) {
            return base.Channel.DeleteBankAccountAsync(bankAccountToDelete);
        }
    }
}
