//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankMVC.CustomerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerService.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/CreateCustomer", ReplyAction="http://tempuri.org/ICustomerService/CreateCustomerResponse")]
        int CreateCustomer(Pocos.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/CreateCustomer", ReplyAction="http://tempuri.org/ICustomerService/CreateCustomerResponse")]
        System.Threading.Tasks.Task<int> CreateCustomerAsync(Pocos.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllCustomers", ReplyAction="http://tempuri.org/ICustomerService/GetAllCustomersResponse")]
        System.Collections.Generic.List<Pocos.Customer> GetAllCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllCustomers", ReplyAction="http://tempuri.org/ICustomerService/GetAllCustomersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Pocos.Customer>> GetAllCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomerById", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerByIdResponse")]
        Pocos.Customer GetCustomerById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetCustomerById", ReplyAction="http://tempuri.org/ICustomerService/GetCustomerByIdResponse")]
        System.Threading.Tasks.Task<Pocos.Customer> GetCustomerByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/DeleteCustomer", ReplyAction="http://tempuri.org/ICustomerService/DeleteCustomerResponse")]
        void DeleteCustomer(Pocos.Customer customerToDelete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/DeleteCustomer", ReplyAction="http://tempuri.org/ICustomerService/DeleteCustomerResponse")]
        System.Threading.Tasks.Task DeleteCustomerAsync(Pocos.Customer customerToDelete);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllCustomerBankAccounts", ReplyAction="http://tempuri.org/ICustomerService/GetAllCustomerBankAccountsResponse")]
        System.Collections.Generic.List<Pocos.BankAccount> GetAllCustomerBankAccounts(Pocos.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/GetAllCustomerBankAccounts", ReplyAction="http://tempuri.org/ICustomerService/GetAllCustomerBankAccountsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Pocos.BankAccount>> GetAllCustomerBankAccountsAsync(Pocos.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/EditCustomer", ReplyAction="http://tempuri.org/ICustomerService/EditCustomerResponse")]
        void EditCustomer(Pocos.Customer customerToEdit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerService/EditCustomer", ReplyAction="http://tempuri.org/ICustomerService/EditCustomerResponse")]
        System.Threading.Tasks.Task EditCustomerAsync(Pocos.Customer customerToEdit);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : BankMVC.CustomerService.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<BankMVC.CustomerService.ICustomerService>, BankMVC.CustomerService.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreateCustomer(Pocos.Customer customer) {
            return base.Channel.CreateCustomer(customer);
        }
        
        public System.Threading.Tasks.Task<int> CreateCustomerAsync(Pocos.Customer customer) {
            return base.Channel.CreateCustomerAsync(customer);
        }
        
        public System.Collections.Generic.List<Pocos.Customer> GetAllCustomers() {
            return base.Channel.GetAllCustomers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Pocos.Customer>> GetAllCustomersAsync() {
            return base.Channel.GetAllCustomersAsync();
        }
        
        public Pocos.Customer GetCustomerById(int id) {
            return base.Channel.GetCustomerById(id);
        }
        
        public System.Threading.Tasks.Task<Pocos.Customer> GetCustomerByIdAsync(int id) {
            return base.Channel.GetCustomerByIdAsync(id);
        }
        
        public void DeleteCustomer(Pocos.Customer customerToDelete) {
            base.Channel.DeleteCustomer(customerToDelete);
        }
        
        public System.Threading.Tasks.Task DeleteCustomerAsync(Pocos.Customer customerToDelete) {
            return base.Channel.DeleteCustomerAsync(customerToDelete);
        }
        
        public System.Collections.Generic.List<Pocos.BankAccount> GetAllCustomerBankAccounts(Pocos.Customer customer) {
            return base.Channel.GetAllCustomerBankAccounts(customer);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Pocos.BankAccount>> GetAllCustomerBankAccountsAsync(Pocos.Customer customer) {
            return base.Channel.GetAllCustomerBankAccountsAsync(customer);
        }
        
        public void EditCustomer(Pocos.Customer customerToEdit) {
            base.Channel.EditCustomer(customerToEdit);
        }
        
        public System.Threading.Tasks.Task EditCustomerAsync(Pocos.Customer customerToEdit) {
            return base.Channel.EditCustomerAsync(customerToEdit);
        }
    }
}
