//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankMVC.DepositingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DepositingService.IDepositingService")]
    public interface IDepositingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepositingService/Deposit", ReplyAction="http://tempuri.org/IDepositingService/DepositResponse")]
        void Deposit(decimal amount, Pocos.BankAccount bankAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepositingService/Deposit", ReplyAction="http://tempuri.org/IDepositingService/DepositResponse")]
        System.Threading.Tasks.Task DepositAsync(decimal amount, Pocos.BankAccount bankAccount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDepositingServiceChannel : BankMVC.DepositingService.IDepositingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DepositingServiceClient : System.ServiceModel.ClientBase<BankMVC.DepositingService.IDepositingService>, BankMVC.DepositingService.IDepositingService {
        
        public DepositingServiceClient() {
        }
        
        public DepositingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DepositingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepositingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepositingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Deposit(decimal amount, Pocos.BankAccount bankAccount) {
            base.Channel.Deposit(amount, bankAccount);
        }
        
        public System.Threading.Tasks.Task DepositAsync(decimal amount, Pocos.BankAccount bankAccount) {
            return base.Channel.DepositAsync(amount, bankAccount);
        }
    }
}
